### ISSUE TITLE
Пример

### ISSUE THREAD

**Issue by dmamontov** [antirek/docker-asterisk15-lua-pjsip-sample#1]
Добрый день! Я понимаю что это пример. Но как произвести тестовый внутренний вызов? все ссылается на sipnet.

**Comment by antirek** [comment]
https://github.com/antirek/docker-asterisk15-lua-pjsip-sample/blob/master/store/etc/asterisk/extensions.lua#L42

вот здесь написан диалплан, например все номера на 1XX идут на dial, который как разу бедте звонить на внутренние через dial(PJSIP/exten)
далее пример звонка на 200, там уже ivr 
а sipnet это уже на исходящие пример

**Comment by dmamontov** [comment]
просто не увидел чтобы гдето ip бы л прописан. К какому просто интересно подключаться.

**Comment by dmamontov** [comment]
нужно ли вообще прокидывать порты и задавать статический ip.

**Comment by dmamontov** [comment]
> https://github.com/antirek/docker-asterisk15-lua-pjsip-sample/blob/master/store/etc/asterisk/extensions.lua#L42
> 
> вот здесь написан диалплан, например все номера на 1XX идут на dial, который как разу бедте звонить на внутренние через dial(PJSIP/exten)
> далее пример звонка на 200, там уже ivr
> а sipnet это уже на исходящие пример

Вы сможете ответить на мои вопросы выше?

**Comment by antirek** [comment]
Нет, я не понимаю ваши вопросы. Переформулируйте их, пожалуйста.

**Comment by dmamontov** [comment]
Есть софтофон установленный на основном пк. как подключиться к вашему проекту для тестов?

**Comment by antirek** [comment]
1. взять сервер с linux
2. настроить на сервере сеть с ip-адресом
3. на сервер поставить docker, docker-compose
4. скачать данный проект
5. выполнить секцию run из readme.md данного проекта
6. со своего ПК подключиться sip-клиентом с учетными данными из pjsip.conf на ip-адрес настроенный в пункте 2.
7. в случае косяков - разобрать логи docker, asterisk

**Comment by dmamontov** [comment]
sip.conf же в примере почти весь закоментирован. В этом и дело что не могу понять как авторизоваться.

**Comment by antirek** [comment]
да, конечно, это ж пример с pjsip - pjsip.conf

**Comment by dmamontov** [comment]
Спасибо. Все заработало!
